---
- name: build Ansible SSA EE
  hosts: localhost

  roles:
    - ee-ansible-ssa
  vars:
    lock_file_path: /tmp/ansible-builder.lock

  pre_tasks:
    - name: check for lock file
      ansible.builtin.stat:
        path: "{{ lock_file_path }}"
      register: lock_file

    - name: wait for lock file to be absent (maximum 2h)
      ansible.builtin.wait_for:
        state: absent
        path: "{{ lock_file_path }}"
        timeout: 7200

    - name: create lock file
      ansible.builtin.file:
        path: "{{ lock_file_path }}"
        state: touch
        mode: 0644

  post_tasks:
    - name: remove lock file
      ansible.builtin.file:
        path: "{{ lock_file_path }}"
        state: absent
