---
- name: log into Red Hat registry
  containers.podman.podman_login:
    username: "{{ registry_redhat_username }}"
    password: "{{ registry_redhat_password }}"
    registry: registry.redhat.io

- name: log into Quay.io registry
  containers.podman.podman_login:
    username: "{{ registry_quay_username }}"
    password: "{{ registry_quay_password }}"
    registry: quay.io

- name: log into private automation hub
  containers.podman.podman_login:
    username: "{{ registry_ah_username }}"
    password: "{{ registry_ah_password }}"
    registry: ah.bolzchristian.de

- name: pull latest version of ee-supported-rhel8 image
  containers.podman.podman_image:
    name: registry.redhat.io/ansible-automation-platform-21/ee-supported-rhel8

- name: pull latest version of ansible-builder image
  containers.podman.podman_image:
    name: registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8

- name: get image information for EE ee-ansible-ssa:{{ ansible_ssa_tag }}
  containers.podman.podman_image_info:
    name: ee-ansible-ssa:{{ ansible_ssa_tag }}
  register: ansible_ssa_image

- name: remove previously built images for ee-ansible-ssa:{{ ansible_ee_tag }}
  ansible.builtin.command: "podman rmi -f {{ item.Id }}"
  changed_when: true
  loop:
    "{{ ansible_ssa_image.images }}"
  when:
    - ansible_ssa_image.images != []

- name: build the new EE version {{ ansible_ssa_tag }} (this might take a few minutes)
  ansible.builtin.shell: ansible-builder build -f ee-ansible-ssa.yml -t ee-ansible-ssa:{{ ansible_ssa_tag }} -v 3 &> ansible-builder.log
  args:
    chdir: ee-ansible-ssa
  when:
    - ansible_ssa_image.images == []

- name: apply image tags locally
  containers.podman.podman_tag:
    image: ee-ansible-ssa:{{ ansible_ssa_tag }}
    target_names: ee-ansible-ssa:latest

- name: push the EE to private Quay registry
  containers.podman.podman_image:
    name: ee-ansible-ssa
    push: true
    pull: false
    tag: "{{ item }}"
    push_args:
      dest: quay.io/redhat_emp1/ee-ansible-ssa:{{ item }}
  loop:
    - "{{ ansible_ssa_tag }}"
    - latest

- name: push the EE to private automation hub
  containers.podman.podman_image:
    name: ee-ansible-ssa
    push: true
    pull: false
    tag: "{{ item }}"
    push_args:
      dest: ah.bolzchristian.de/ee-ansible-ssa:{{ item }}
  loop:
    - "{{ ansible_ssa_tag }}"
    - latest

- name: trigger the internal CI/CD pipeline
  ansible.builtin.uri:
    url: https://controller.bolzchristian.de/api/v2/workflow_job_templates/CI%20-%20RHAAP%20Workflow++Default/launch/
    method: POST
    user: gitlab
    password: "{{ controller_password }}"
    force_basic_auth: true
    status_code:
      - 201
      - 200
