---
- name: log into Red Hat registry
  containers.podman.podman_login:
    username: "{{ registry_redhat_username }}"
    password: "{{ registry_redhat_password }}"
    registry: registry.redhat.io

- name: log into GitLab registry
  containers.podman.podman_login:
    username: "{{ registry_gitlab_username }}"
    password: "{{ registry_gitlab_password }}"
    registry: registry.gitlab.com

- name: log into private automation hub
  containers.podman.podman_login:
    username: "{{ registry_ah_username }}"
    password: "{{ registry_ah_password }}"
    registry: ah.bolzchristian.de

- name: pull latest version of ee-supported-rhel8
  containers.podman.podman_image:
    name: registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8

- name: pull latest version of ansible-builder
  containers.podman.podman_image:
    name: quay.io/ansible/ansible-builder

- name: get image information
  containers.podman.podman_image_info:
    name: ee-ansible-ssa:{{ ansible_ssa_tag }}
  register: ansible_ssa_image

- name: build the new EE if it doesn't exist (this might take a few minutes)
  ansible.builtin.command: ansible-builder build -f ee-ansible-ssa.yml -t ee-ansible-ssa:{{ ansible_ssa_tag }} -v 3
  args:
    chdir: ee-ansible-ssa
  when:
    - ansible_ssa_image.images == []

# log into the Red Hat registry to be able to pull the ee-supported-rhel8
# podman login registry.redhat.io
# # pull latest version of the image
# podman pull registry.redhat.io/ansible-automation-platform-20-early-access/ee-supported-rhel8
# # make sure helper images are up to date
# podman pull quay.io/ansible/ansible-builder
# cd ee-ansible-ssa
# # set tag to the proper version, e.g
# tag=0.4.10
# ansible-builder build -f ee-ansible-ssa.yml -t ee-ansible-ssa:$tag
# # you might want to add -v 3 to get more details
# ansible-builder build -f ee-ansible-ssa.yml -t ee-ansible-ssa:$tag -v 3
# ```

# ## Push the image

# ```bash
# podman login registry.gitlab.com
# podman push ee-ansible-ssa:$tag registry.gitlab.com/redhat-cop/ansible-ssa/ee-ansible-ssa/ee-ansible-ssa:$tag
# podman push ee-ansible-ssa:$tag registry.gitlab.com/redhat-cop/ansible-ssa/ee-ansible-ssa/ee-ansible-ssa:latest
# ```

# ## Ansible Navigator

# The classic `ansible-playbook` command does not provide support for execution environments. Install [ansible-navigator](https://github.com/ansible/ansible-navigator) manually or from the [Red Hat Software Channel](https://access.redhat.com/documentation/en-us/red_hat_ansible_automation_platform/2.0-ea/html-single/ansible_navigator_creator_guide/index#assembly-installing_on_rhel_ansible-navigator).

# The `--eei` command line option allows you to specify which execution environment should be used when running an Ansible Playbook. For convenience it is recommended to add the setting to your personal `~/.ansible-navigator.yml` configuration file.
