---
collections:
  - name: amazon.aws
    version: 3.3.0
  - name: ansible.controller
    version: 4.1.2
  - name: ansible.posix
    version: 1.4.0
  - name: ansible.windows
    version: 1.10.0
  - name: ansible_ssa.general
  - name: azure.azcollection
    version: 1.13.0
  - name: chocolatey.chocolatey
    version: 1.0.2
  - name: community.aws
    version: 3.2.0
  - name: community.crypto
    version: 2.3.2
  - name: community.general
    version: 5.1.0
  - name: community.mysql
    version: 3.3.0
  - name: community.windows
    version: 1.10.0
  - name: containers.podman
    version: 1.9.3
  - name: freeipa.ansible_freeipa
    version: 1.7.0
  - name: google.cloud
    version: 1.0.2
  - name: redhat.rhel_system_roles
    version: 1.16.2
