---
collections:
  - name: amazon.aws
    version: 1.5.0
  - name: ansible.controller
    version: 4.0.0
  - name: ansible.posix
    version: 1.3.0
  - name: ansible_ssa.general
    version: 3.1.4
  - name: community.aws
    version: 1.5.0
  - name: community.crypto
    version: 1.8.0
  - name: community.general
    version: 3.5.0
  - name: freeipa.ansible_freeipa
    version: 0.3.8
